#! /bin/bash
#This Bash script will determine if a file path is blocked device or Character device
read -p "Enter a File Path: " file_path
if [ ! -e $file_path ];
then
echo "file does not exist."
fi
if [ -b $file_path ];
then 
echo "This file is a block Device."
elif [ -c $file_path ];
then
echo "This is a character Device."
else
echo  "The file path is niether a block device or a character device"
fi
